spring.autoconfigure.exclude:
- org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
- org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration



User:
  username: ""
  password: ""
  database: ""

Encryption:
  PasswordStrength: "10"

Application:
  AppName: "School Project"
  DatabaseName: "CareerDay"