spring.autoconfigure.exclude:
- org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
- org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration



User:
  username: "BackEnd"
  password: "zde53Y9ERTpmBRYR"
  database: "warhammerproject"

Encryption:
  PasswordStrength: "10"

Application:
  AppName: "Warhammer40k"
  DatabaseName: "Warhammer40k"